from typing import Any
import logging

TRANSCRIBE_BACKEND: str

FASTER_WHISPER_MODEL: str
FASTER_WHISPER_DEVICE: str
FASTER_WHISPER_COMPUTE_TYPE: str
FASTER_WHISPER_BEAM_SIZE: int
FASTER_WHISPER_BEST_OF: int
FASTER_WHISPER_VAD_FILTER: bool
FASTER_WHISPER_CONDITION_ON_PREVIOUS_TEXT: bool

ASR_MIN_LANGUAGE_PROB: float
ASR_MIN_AVG_LOGPROB: float
ASR_MAX_REPETITION_RATIO: float
ASR_MAX_SEGMENT_DURATION: float
ASR_AUDIO_PREPROCESS_ENABLED: bool
ASR_AUDIO_FILTER: str
ASR_REFINE_LOW_CONF_SEGMENTS_ENABLED: bool
ASR_REFINE_MAX_SEGMENTS: int
ASR_REFINE_MARGIN_SEC: float
ASR_RETRY_ON_LOW_QUALITY_ENABLED: bool
ASR_RETRY_MODEL: str
ASR_RETRY_BEAM_SIZE: int
ASR_RETRY_BEST_OF: int
ASR_RETRY_VAD_FILTER: bool
ASR_RETRY_CONDITION_ON_PREVIOUS_TEXT: bool
ASR_SKIP_SUSPICIOUS_SEGMENTS: bool
ASR_SKIP_SUSPICIOUS_MAX_RATIO: float

WHISPERX_MODEL: str
WHISPERX_COMPUTE_TYPE: str
WHISPERX_BATCH_SIZE: int
WHISPERX_DIARIZE_ENABLED: bool
WHISPERX_ALIGN_ENABLED: bool
HF_TOKEN: str

NVIDIA_API_KEY: str
NVIDIA_BASE_URL: str
NVIDIA_WHISPER_MODEL: str
NVIDIA_MAXINE_API_KEY: str
NVIDIA_MAXINE_BASE_URL: str

TRANSLATION_BACKEND: str
TRANSLATION_ENABLE_SMART_ROUTING: bool
INDICTRANS2_EN_INDIC_MODEL: str
INDICTRANS2_INDIC_EN_MODEL: str

TTS_BACKEND: str
TTS_REF_AUDIO: str
TTS_REF_TEXT: str
TTS_CROSSFADE_MS: int
SEPARATION_BACKEND: str
SEPARATION_MODEL: str
SEPARATION_DEVICE: str
TTS_DURATION_MATCH_MIN_SPEED: float
TTS_DURATION_MATCH_MAX_SPEED: float
TTS_DURATION_MATCH_EN_MIN_SPEED: float | None
TTS_DURATION_MATCH_EN_MAX_SPEED: float | None
TTS_DURATION_LOCK_ENABLED: bool
TTS_DURATION_LOCK_TOLERANCE_SEC: float
TTS_DURATION_FORCE_EXACT_FIT: bool
TTS_SPEAKER_REF_MAX_SECONDS: float
TTS_UNLOAD_MODEL_BETWEEN_CHUNKS: bool

QWEN3_LOCAL_MODEL_ID: str
QWEN3_LOCAL_DTYPE: str
QWEN3_LOCAL_MAX_CHARS_PER_CHUNK: int
QWEN3_LOCAL_TEMPERATURE: float
QWEN3_EXPRESSIVE_ENGLISH_ENABLED: bool
QWEN3_EXPRESSIVE_ENGLISH_BOOST: float
QWEN3_LOW_VRAM_MAX_CHARS_PER_CHUNK: int
QWEN3_MID_VRAM_MAX_CHARS_PER_CHUNK: int
QWEN3_HIGH_VRAM_MAX_CHARS_PER_CHUNK: int
QWEN3_LOW_VRAM_BATCH_SIZE: int
QWEN3_MID_VRAM_BATCH_SIZE: int
QWEN3_HIGH_VRAM_BATCH_SIZE: int
QWEN3_LOW_VRAM_CLEANUP_EVERY: int
QWEN3_MID_VRAM_CLEANUP_EVERY: int
QWEN3_HIGH_VRAM_CLEANUP_EVERY: int

FORCE_CPU_FOR_TTS: bool
GPU_MEMORY_FRACTION: float
ADAPTIVE_RUNTIME_ENABLED: bool
LOW_VRAM_THRESHOLD_GB: float
MID_VRAM_THRESHOLD_GB: float
HIGH_VRAM_THRESHOLD_GB: float
OUTPUT_DIR: str
TEMP_DIR: str
LOG_LEVEL: str
BENCHMARK_DIR: str
BENCHMARK_AUTO_SAVE: bool

def validate() -> None: ...
def get_logger(name: str) -> logging.Logger: ...
def get_runtime_profile(force_refresh: bool = False) -> dict[str, Any]: ...
def setup_gpu_memory_limit() -> None: ...
def print_vram_status() -> dict[str, float] | None: ...
def __getattr__(name: str) -> Any: ...
